---
title: "事前分析"
author: '@nozma'
date: "2/17/2020"
output: html_document
---

```{r setup, include=FALSE}
library(readxl)
library(dplyr)
library(purrr)
library(tidyr)
library(ggplot2)
library(ggdark)
theme_set(dark_theme_classic(base_family = "IPAexGothic"))
```


```{r}
table1 <- read_excel("../data/data.xlsx", sheet = "table1")
table2 <- read_excel("../data/data.xlsx", sheet = "table2")
table3 <- read_excel("../data/data.xlsx", sheet = "table3")
```

```{r}
calc_chisq_p <- function(dominant, recessive, expected, target = "chisq"){
  p <- case_when(
    grepl("3:1", expected) ~ c(3/4, 1/4),
    grepl("2:1", expected) ~ c(2/3, 1/3),
    grepl("1:1", expected) ~ c(1/2, 1/2)
  )
  result <- chisq.test(
    c(dominant, recessive), 
    correct = FALSE,
    p = p
  )
  if(target == "chisq"){
    return(result$statistic)
  } else {
    return(result$p.value)
  }
}
```

p値とχ²値を再計算

```{r}
table1 %>% 
  mutate(
    `chi-square` = pmap_dbl(
      list(dominant = dominant, recessive = recessive,
           expected = expected, target = "chisq"),
      calc_chisq_p
    ),
    P = pmap_dbl(
      list(dominant = dominant, recessive = recessive,
           expected = expected, target = "p"),
      calc_chisq_p
    )
  ) -> table1
table2 %>% 
  mutate(
    `chi-square` = pmap_dbl(
      list(dominant = dominant, recessive = recessive,
           expected = "3:1", target = "chisq"),
      calc_chisq_p
    ),
    P = pmap_dbl(
      list(dominant = dominant, recessive = recessive,
           expected = "3:1", target = "p"),
      calc_chisq_p
    )
  ) -> table2
table3 %>% 
  mutate(
    `chi-square` = pmap_dbl(
      list(dominant = dominant, recessive = recessive,
           expected = expected, target = "chisq"),
      calc_chisq_p
    ),
    P = pmap_dbl(
      list(dominant = dominant, recessive = recessive,
           expected = expected, target = "p"),
      calc_chisq_p
    )
  ) -> table3
```

## 「適合しすぎている」を検証する

phenotype単位でχ²値と自由度を計算。

```{r}
table1 %>% 
  group_by(phenotype) %>% 
  summarise(
    `chi-square` = sum(`chi-square`),
    df = n()
  ) %>% 
  mutate(
    p = pchisq(`chi-square`, df, lower.tail = FALSE)
  )
```

すべてをプールして計算。

```{r}
table1 %>% 
  summarise(
    `chi-square` = sum(`chi-square`),
    df = n()
  ) %>% 
  mutate(
    p = pchisq(`chi-square`, df, lower.tail = FALSE)
  )
```

table3について同様の計算。まず形質ごとに。

```{r}
table3 %>% 
  group_by(phenotype) %>% 
  summarise(
    `chi-square` = sum(`chi-square`),
    df = n()
  ) %>% 
  mutate(
    p = round(pchisq(`chi-square`, df, lower.tail = FALSE), 5)
  )
```

全体をプールして。

```{r}
table3 %>% 
  summarise(
    `chi-square` = sum(`chi-square`),
    df = n()
  ) %>% 
  mutate(
    p = round(pchisq(`chi-square`, df, lower.tail = FALSE), 5)
  )
```

## P値の分布について調査する

### そもそもP値の分布はどうなるか

- 検証方針
  - 3:1を期待比率とする二項乱数を生成し、それに基づくP値を計算する。

```{r}
rbinom(2000, 1000, 3/4) %>% 
  map_dbl(
    function(x){
      chisq.test(
        c(x, 1000 - x),
        p = c(3/4, 1/4)
      )$p.value
    }
  ) -> p.values
ggplot() +
  geom_histogram(
    aes(x = p.values),
    binwidth = 0.05, boundary = 0
  )
```


### データソースごとの分布

3つのテーブルを結合する。

```{r}
joint_table <- table1 %>% 
  mutate(table_source = "Mendel") %>% 
  union_all(
    table2 %>% mutate(table_source = "Johannsen")
  ) %>% 
  union_all(
    table3 %>% mutate(table_source = "linkage")
  )
joint_table
```

```{r}
joint_table %>% 
  filter(table_source != "Johannsen") %>% 
  ggplot(aes(x = P)) +
  geom_histogram(
    aes(y = ..density.. * 0.05),
    binwidth = 0.05, boundary = 0
    ) +
  geom_hline(yintercept = 0.05, col = "turquoise") +
  geom_vline(xintercept = 0.35, col = "orange") +
  facet_grid(table_source ~ ., scales = "free_y") +
  labs(x = "P値", y = "相対度数") -> p
ggsave("../figure/p-plot.png", width = 3.5, height = 2.5)
```

### カイ二乗分布の和

```{r}
n = 100000
tibble(
  `自由度1の分布5つの和` = rchisq(n, df = 1) + rchisq(n, df = 1) + rchisq(n, df = 1) + rchisq(n, df = 1) + rchisq(n, df = 1),
  `自由度5の分布` = rchisq(n, df = 5)
  ) %>% 
  pivot_longer(cols = everything()) %>% 
  ggplot(aes(x = value)) +
  facet_grid(name ~ .) +
  geom_density(alpha = .5)
```

## 曖昧なデータと曖昧ではないデータ


```{r}
table4 <- read_excel("../data/data.xlsx", sheet = "table4_5")
table4 %>% 
  group_by(Source, Trait) %>% 
  summarise(low = sum(low), high = sum(high)) %>%
  mutate(
    chisq = 
      (low - (low + high)/2)^2 / ((low + high)/2) * 2,
    P = pchisq(chisq, 1, lower.tail = FALSE)
  )
```

```{r}

```

